name: opti-de-redes
channels:
  - conda-forge
  - gurobi
dependencies:
  - python=3.13
  - numpy
  - matplotlib
  - pandas
  - scipy
  - gurobi
  - cobra
  - wcwidth
  - jupyter
  - ipykernel
  - seaborn